"""empty message

Revision ID: 1427acb17d2a
Revises: 211c9e8ab644
Create Date: 2024-11-25 01:40:00.216601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1427acb17d2a'
down_revision = '211c9e8ab644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_in_day', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('check_in_month', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('check_in_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('check_out_day', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('check_out_month', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('check_out_month')
        batch_op.drop_column('check_out_day')
        batch_op.drop_column('check_in_year')
        batch_op.drop_column('check_in_month')
        batch_op.drop_column('check_in_day')

    # ### end Alembic commands ###
