"""empty message

Revision ID: 211c9e8ab644
Revises: 0007017cc608
Create Date: 2024-11-24 04:03:34.298516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '211c9e8ab644'
down_revision = '0007017cc608'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint('bookings_ibfk_1', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_foreign_key('bookings_ibfk_1', 'users', ['creator_id'], ['uid'])

    # ### end Alembic commands ###
