"""empty message

Revision ID: 419ba66fe80e
Revises: d66ccdf6b7b4
Create Date: 2025-04-14 02:15:25.731473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '419ba66fe80e'
down_revision = 'd66ccdf6b7b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rate_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('property_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'properties', ['property_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rate_plans', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('property_id')

    # ### end Alembic commands ###
