"""empty message

Revision ID: 457d05a7d6ca
Revises: 6fe511b5de6a
Create Date: 2026-03-31 12:22:19.076740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '457d05a7d6ca'
down_revision = '6fe511b5de6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_property_access', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_status_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_property_access', schema=None) as batch_op:
        batch_op.drop_column('account_status_id')

    # ### end Alembic commands ###
