"""empty message

Revision ID: 5f9cff1a83cd
Revises: 8e668cea8f2a
Create Date: 2026-04-06 15:36:25.905551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f9cff1a83cd'
down_revision = '8e668cea8f2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_cleaning_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('color', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cleaning_status_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'room_cleaning_status', ['cleaning_status_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cleaning_status_id')

    op.drop_table('room_cleaning_status')
    # ### end Alembic commands ###
