"""empty message

Revision ID: 665769c0a450
Revises: 
Create Date: 2025-04-16 02:00:37.726831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '665769c0a450'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rate_plans', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'properties', ['property_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rate_plans', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
