"""empty message

Revision ID: 685d59367c30
Revises: b0f9d298da38
Create Date: 2025-05-12 01:47:17.513197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '685d59367c30'
down_revision = 'b0f9d298da38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
