"""empty message

Revision ID: 6fe511b5de6a
Revises: b1bc04512669
Create Date: 2026-03-31 11:44:12.134152

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6fe511b5de6a'
down_revision = 'b1bc04512669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_property_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'property_id', name='uq_user_property_role')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('permissions_json', sa.JSON(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_roles_default'))
        batch_op.drop_column('default')
        batch_op.drop_column('permissions')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_super_admin', sa.Boolean(), nullable=True))
        batch_op.drop_constraint(batch_op.f('users_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('users_ibfk_1'), 'roles', ['role_id'], ['id'])
        batch_op.drop_column('is_super_admin')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permissions', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('default', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_roles_default'), ['default'], unique=False)
        batch_op.drop_column('permissions_json')
        batch_op.drop_column('description')

    op.drop_table('user_property_access')
    # ### end Alembic commands ###
