"""add channel manager tables

Revision ID: 812cf49f3dc5
Revises: 685d59367c30
Create Date: 2026-03-27 15:38:06.003535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '812cf49f3dc5'
down_revision = '685d59367c30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('channel_code', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('credentials_json', sa.JSON(), nullable=False),
    sa.Column('settings_json', sa.JSON(), nullable=False),
    sa.Column('polling_enabled', sa.Boolean(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'channel_code', name='uq_channel_connection_property_channel')
    )
    with op.batch_alter_table('channel_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channel_connections_channel_code'), ['channel_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_connections_property_id'), ['property_id'], unique=False)

    op.create_table('channel_sync_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('channel_code', sa.String(length=32), nullable=False),
    sa.Column('job_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('channel_sync_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channel_sync_jobs_channel_code'), ['channel_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_sync_jobs_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_sync_jobs_job_type'), ['job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_sync_jobs_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_sync_jobs_status'), ['status'], unique=False)

    op.create_table('channel_message_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('channel_code', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('message_type', sa.String(length=32), nullable=False),
    sa.Column('related_job_id', sa.Integer(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('request_body', sa.Text(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['related_job_id'], ['channel_sync_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('channel_message_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channel_message_logs_channel_code'), ['channel_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_message_logs_property_id'), ['property_id'], unique=False)

    op.create_table('channel_rate_plan_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('channel_code', sa.String(length=32), nullable=False),
    sa.Column('internal_rate_plan_id', sa.Integer(), nullable=False),
    sa.Column('external_rate_plan_id', sa.String(length=128), nullable=False),
    sa.Column('external_rate_plan_name', sa.String(length=255), nullable=True),
    sa.Column('pricing_model', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['internal_rate_plan_id'], ['rate_plans.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'channel_code', 'external_rate_plan_id', name='uq_rate_map_external'),
    sa.UniqueConstraint('property_id', 'channel_code', 'internal_rate_plan_id', name='uq_rate_map_internal')
    )
    with op.batch_alter_table('channel_rate_plan_maps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channel_rate_plan_maps_channel_code'), ['channel_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_rate_plan_maps_internal_rate_plan_id'), ['internal_rate_plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_rate_plan_maps_property_id'), ['property_id'], unique=False)

    op.create_table('channel_room_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('channel_code', sa.String(length=32), nullable=False),
    sa.Column('internal_room_id', sa.Integer(), nullable=False),
    sa.Column('external_room_id', sa.String(length=128), nullable=False),
    sa.Column('external_room_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['internal_room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'channel_code', 'external_room_id', name='uq_room_map_external'),
    sa.UniqueConstraint('property_id', 'channel_code', 'internal_room_id', name='uq_room_map_internal')
    )
    with op.batch_alter_table('channel_room_maps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channel_room_maps_channel_code'), ['channel_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_room_maps_internal_room_id'), ['internal_room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_room_maps_property_id'), ['property_id'], unique=False)

    op.create_table('channel_reservation_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('channel_code', sa.String(length=32), nullable=False),
    sa.Column('external_reservation_id', sa.String(length=128), nullable=False),
    sa.Column('external_version', sa.String(length=128), nullable=True),
    sa.Column('internal_booking_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['internal_booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'channel_code', 'external_reservation_id', name='uq_channel_reservation_link')
    )
    with op.batch_alter_table('channel_reservation_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channel_reservation_links_channel_code'), ['channel_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_reservation_links_external_reservation_id'), ['external_reservation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_reservation_links_internal_booking_id'), ['internal_booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_reservation_links_property_id'), ['property_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channel_reservation_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channel_reservation_links_property_id'))
        batch_op.drop_index(batch_op.f('ix_channel_reservation_links_internal_booking_id'))
        batch_op.drop_index(batch_op.f('ix_channel_reservation_links_external_reservation_id'))
        batch_op.drop_index(batch_op.f('ix_channel_reservation_links_channel_code'))

    op.drop_table('channel_reservation_links')
    with op.batch_alter_table('channel_room_maps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channel_room_maps_property_id'))
        batch_op.drop_index(batch_op.f('ix_channel_room_maps_internal_room_id'))
        batch_op.drop_index(batch_op.f('ix_channel_room_maps_channel_code'))

    op.drop_table('channel_room_maps')
    with op.batch_alter_table('channel_rate_plan_maps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channel_rate_plan_maps_property_id'))
        batch_op.drop_index(batch_op.f('ix_channel_rate_plan_maps_internal_rate_plan_id'))
        batch_op.drop_index(batch_op.f('ix_channel_rate_plan_maps_channel_code'))

    op.drop_table('channel_rate_plan_maps')
    with op.batch_alter_table('channel_message_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channel_message_logs_property_id'))
        batch_op.drop_index(batch_op.f('ix_channel_message_logs_channel_code'))

    op.drop_table('channel_message_logs')
    with op.batch_alter_table('channel_sync_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channel_sync_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_channel_sync_jobs_property_id'))
        batch_op.drop_index(batch_op.f('ix_channel_sync_jobs_job_type'))
        batch_op.drop_index(batch_op.f('ix_channel_sync_jobs_correlation_id'))
        batch_op.drop_index(batch_op.f('ix_channel_sync_jobs_channel_code'))

    op.drop_table('channel_sync_jobs')
    with op.batch_alter_table('channel_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channel_connections_property_id'))
        batch_op.drop_index(batch_op.f('ix_channel_connections_channel_code'))

    op.drop_table('channel_connections')
    # ### end Alembic commands ###
