"""empty message

Revision ID: 98d718f3c8c7
Revises: 
Create Date: 2024-02-13 08:28:52.865807

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '98d718f3c8c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('title', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('routing', sa.String(length=32), nullable=True))
        batch_op.drop_column('subject')
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('subject', mysql.TEXT(), nullable=True))
        batch_op.drop_column('routing')
        batch_op.drop_column('title')
        batch_op.drop_column('body')

    # ### end Alembic commands ###
