"""empty message

Revision ID: e1843801a162
Revises: 
Create Date: 2026-04-05 13:06:14.894493

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e1843801a162'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('categories_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('property_id')

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=32),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.drop_column('city')
        batch_op.drop_column('amenities')
        batch_op.drop_column('country')
        batch_op.drop_column('latitude')
        batch_op.drop_column('longitude')
        batch_op.drop_column('policies')
        batch_op.drop_column('property_type')
        batch_op.drop_column('check_in_time')
        batch_op.drop_column('check_out_time')
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('check_out_time', mysql.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('check_in_time', mysql.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('property_type', mysql.VARCHAR(length=32), nullable=True))
        batch_op.add_column(sa.Column('policies', mysql.JSON(), nullable=True))
        batch_op.add_column(sa.Column('longitude', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('latitude', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('country', mysql.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('amenities', mysql.JSON(), nullable=True))
        batch_op.add_column(sa.Column('city', mysql.VARCHAR(length=64), nullable=True))
        batch_op.alter_column('address',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(length=64),
               nullable=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('property_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('categories_ibfk_1'), 'properties', ['property_id'], ['id'])

    # ### end Alembic commands ###
